In [ ]:
! pip install stg

In [ ]:
import pandas as pd
from stg import STG
import numpy as np
import torch
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
def one_hot_encode(df_test):
    """[One hot encode all features but the players name and the kickoff time]

    Args:
        df ([type]): [description]

    Returns:
        [type]: [description]
    """
    cat = df_test.select_dtypes(exclude='number').columns.drop(['player_name', 'kickoff_time']) 
    df_test = pd.get_dummies(df_test, columns=cat, prefix=cat)
    return df_test

df = pd.read_csv('/content/drive/MyDrive/Data/collected_us.csv')
df = one_hot_encode(df)
df = df.drop(columns = ['player_name', 'kickoff_time'])
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['total_points']),
                                                    df['total_points'],
                                                    train_size=0.9)
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, train_size=0.8)

num_feats = df.select_dtypes(include='number').drop(columns = ['total_points']).columns
std_scaler_X, std_scaler_Y = StandardScaler(), StandardScaler()
df[num_feats] = std_scaler_X.fit_transform(df[num_feats])
df['total_points'] = std_scaler_Y.fit_transform(df['total_points'].to_numpy().reshape(-1, 1))


In [ ]:
# args_cuda = torch.cuda.is_available()
# device = torch.device("cuda" if args_cuda else "cpu") 
# feature_selection = True
# model = STG(task_type='regression',input_dim=X_train.shape[1], output_dim=1, hidden_dims=[500, 50, 10], activation='tanh',
#     optimizer='SGD', learning_rate=0.1, batch_size=X_train.shape[0], feature_selection=feature_selection, sigma=0.5, lam=0.1, random_state=1, device=device)

In [ ]:
args_cuda = torch.cuda.is_available()
device = torch.device("cuda" if args_cuda else "cpu") 
model_1 = STG(task_type='regression',
            input_dim=X_train.shape[1],
            output_dim=1, hidden_dims=[500, 500, 10], 
            activation='tanh', optimizer='Adam', 
            batch_size=1000, feature_selection=True,
            sigma=0.5, lam=0.1, random_state=1, 
            device=device)
model_1.fit(X_train.to_numpy(), y_train.to_numpy(), nr_epochs=10000, valid_X=X_valid.to_numpy(), valid_y=y_valid.to_numpy(), print_interval=1000)
model_1.get_gates(mode='prob')

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([1000])) that is different to the input size (torch.Size([1000, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([182])) that is different to the input size (torch.Size([182, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([796])) that is different to the input size (torch.Size([796, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(i

Epoch: 1000: loss=9.396727 valid_loss=8.914227
Epoch: 2000: loss=9.121513 valid_loss=8.694063
Epoch: 3000: loss=9.110545 valid_loss=8.694158
Epoch: 4000: loss=9.099881 valid_loss=8.694168
Epoch: 5000: loss=9.091145 valid_loss=8.694057
Epoch: 6000: loss=9.090299 valid_loss=8.694093
Epoch: 7000: loss=9.089788 valid_loss=8.693920
Epoch: 8000: loss=9.089512 valid_loss=8.694031
Epoch: 9000: loss=9.089415 valid_loss=8.694071
Epoch: 10000: loss=9.088988 valid_loss=8.694114


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.40309405, 0.        , 0.        , 0.        , 0.1901471 ,
       0.37381482, 0.39817762, 0.        , 0.        , 0.        ,
       0.13108307, 0.08375868, 0.0783484 , 0.09804624, 0.212078  ,
       0.14880225, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.22764117,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
model_2 = STG(task_type='regression',
            input_dim=X_train.shape[1],
            output_dim=1, hidden_dims=[500, 500, 10], 
            activation='tanh', optimizer='Adam', 
            batch_size=1000, feature_selection=True,
            sigma=0.5, lam=1, random_state=1, 
            device=device)
model_2.fit(X_train.to_numpy(), y_train.to_numpy(), nr_epochs=10000, valid_X=X_valid.to_numpy(), valid_y=y_valid.to_numpy(), print_interval=1000)
model_2.get_gates(mode='prob')

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([1000])) that is different to the input size (torch.Size([1000, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([182])) that is different to the input size (torch.Size([182, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([796])) that is different to the input size (torch.Size([796, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(i

Epoch: 1000: loss=9.947467 valid_loss=8.793331
Epoch: 2000: loss=9.710049 valid_loss=8.694086
Epoch: 3000: loss=9.592251 valid_loss=8.693769
Epoch: 4000: loss=9.473643 valid_loss=8.693996
Epoch: 5000: loss=9.364418 valid_loss=8.694068
Epoch: 6000: loss=9.275361 valid_loss=8.693905
Epoch: 7000: loss=9.210593 valid_loss=8.694105
Epoch: 8000: loss=9.167796 valid_loss=8.695414
Epoch: 9000: loss=9.140938 valid_loss=8.695639
Epoch: 10000: loss=9.133689 valid_loss=8.694740


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.3183236 , 0.        , 0.        , 0.        , 0.        ,
       0.11706156, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
model = STG(task_type='regression',
            input_dim=X_train.shape[1],
            output_dim=1, hidden_dims=[500, 500, 10], 
            activation='tanh', optimizer='Adam', 
            learning_rate = 1e-3, batch_size=1000, feature_selection=True,
            sigma=0.5, lam=10, random_state=1, 
            device=device)
model.fit(X_train.to_numpy(), y_train.to_numpy(), nr_epochs=10000, valid_X=X_valid.to_numpy(), valid_y=y_valid.to_numpy(), print_interval=1000)
model.get_gates(mode='prob')

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([1000])) that is different to the input size (torch.Size([1000, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([182])) that is different to the input size (torch.Size([182, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([796])) that is different to the input size (torch.Size([796, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(i

Epoch: 1000: loss=16.700958 valid_loss=8.754470
Epoch: 2000: loss=15.507972 valid_loss=8.694247
Epoch: 3000: loss=14.275728 valid_loss=8.694243
Epoch: 4000: loss=13.041790 valid_loss=8.697556
Epoch: 5000: loss=11.970069 valid_loss=8.696157
Epoch: 6000: loss=11.065308 valid_loss=9.022763
Epoch: 7000: loss=10.394793 valid_loss=8.715897
Epoch: 8000: loss=9.886919 valid_loss=8.693138
Epoch: 9000: loss=9.568016 valid_loss=8.692205
Epoch: 10000: loss=9.334016 valid_loss=8.692654


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)

(21087, 95)